name: fixed-term-loan-manager
version: 2.0.0
source: contracts
packages:
  - path: contracts/proxy/LoanManagerFactory.sol
    contractName: LoanManagerFactory
  - path: contracts/proxy/LoanManagerInitializer.sol
    contractName: LoanManagerInitializer
  - path: contracts/proxy/LoanManagerStorage.sol
    contractName: LoanManagerStorage
  - path: contracts/LoanManager.sol
    contractName: LoanManager
customDescription: Fixed Term Loan Manager V2 Artifacts and ABIs
